//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemcConfig.Localisation.LocalisationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FemcConfig.Localisation.LocalisationResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Femc Config Adjuster.
        /// </summary>
        public static string About_text {
            get {
                return ResourceManager.GetString("About text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string Addons {
            get {
                return ResourceManager.GetString("Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantage Battle Music.
        /// </summary>
        public static string Advantage_Battle_Music {
            get {
                return ResourceManager.GetString("Advantage Battle Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOA.
        /// </summary>
        public static string AOA {
            get {
                return ResourceManager.GetString("AOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOA Text.
        /// </summary>
        public static string AOA_Text {
            get {
                return ResourceManager.GetString("AOA Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss Battle Music.
        /// </summary>
        public static string Boss_Battle_Music {
            get {
                return ResourceManager.GetString("Boss Battle Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bustup.
        /// </summary>
        public static string Bustup {
            get {
                return ResourceManager.GetString("Bustup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutin.
        /// </summary>
        public static string Cutin {
            get {
                return ResourceManager.GetString("Cutin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime Outside Music (Phase 1).
        /// </summary>
        public static string Daytime_Outside_Music__Phase_1_ {
            get {
                return ResourceManager.GetString("Daytime Outside Music (Phase 1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime School Music (Phase 1).
        /// </summary>
        public static string Daytime_School_Music__Phase_1_ {
            get {
                return ResourceManager.GetString("Daytime School Music (Phase 1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime School Music (Phase 2).
        /// </summary>
        public static string Daytime_School_Music__Phase_2_ {
            get {
                return ResourceManager.GetString("Daytime School Music (Phase 2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disadvantage Battle Music.
        /// </summary>
        public static string Disadvantage_Battle_Music {
            get {
                return ResourceManager.GetString("Disadvantage Battle Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡Tip: If you already have the mod downloaded. Try clicking on configure mod in Reloaded-II..
        /// </summary>
        public static string DownloadTip {
            get {
                return ResourceManager.GetString("DownloadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Battle Music.
        /// </summary>
        public static string Final_Battle_Music {
            get {
                return ResourceManager.GetString("Final Battle Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendered Audio.
        /// </summary>
        public static string Gendered_Audio {
            get {
                return ResourceManager.GetString("Gendered Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Shard.
        /// </summary>
        public static string Glass_Shard {
            get {
                return ResourceManager.GetString("Glass Shard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Photo.
        /// </summary>
        public static string Group_Photo {
            get {
                return ResourceManager.GetString("Group Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyoto Photos.
        /// </summary>
        public static string Kyoto_Photos {
            get {
                return ResourceManager.GetString("Kyoto Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the app has been changed, please restart the app for changes to appear..
        /// </summary>
        public static string LanguageChangeAlert {
            get {
                return ResourceManager.GetString("LanguageChangeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up Screen.
        /// </summary>
        public static string Level_Up_Screen {
            get {
                return ResourceManager.GetString("Level Up Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is unable to initiate the download due to missing info. Please install this mod manually..
        /// </summary>
        public static string Mod_Download_Error {
            get {
                return ResourceManager.GetString("Mod Download Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your download has been initiated. You might need to launch the game and restart the app for changes to appear..
        /// </summary>
        public static string Mod_Download_Start {
            get {
                return ResourceManager.GetString("Mod Download Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we load the Mod Download....
        /// </summary>
        public static string ModDownloadWait {
            get {
                return ResourceManager.GetString("ModDownloadWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Outside Music (Phase 1).
        /// </summary>
        public static string Night_Outside_Music__Phase_1_ {
            get {
                return ResourceManager.GetString("Night Outside Music (Phase 1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Battle Music.
        /// </summary>
        public static string Normal_Battle_Music {
            get {
                return ResourceManager.GetString("Normal Battle Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Panel.
        /// </summary>
        public static string Party_Panel {
            get {
                return ResourceManager.GetString("Party Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalisation.
        /// </summary>
        public static string Personalisation {
            get {
                return ResourceManager.GetString("Personalisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and select your Reloaded II install (exe) to continue..
        /// </summary>
        public static string ReloadExePrompt {
            get {
                return ResourceManager.GetString("ReloadExePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string SelectLanguageText {
            get {
                return ResourceManager.GetString("SelectLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Link Music.
        /// </summary>
        public static string Social_Link_Music {
            get {
                return ResourceManager.GetString("Social Link Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Femc Mod.
        /// </summary>
        public static string The_Femc_Mod {
            get {
                return ResourceManager.GetString("The Femc Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking for updates..
        /// </summary>
        public static string Update_Check_Fail {
            get {
                return ResourceManager.GetString("Update Check Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can update later from the settings or when the application restarts..
        /// </summary>
        public static string Update_Later {
            get {
                return ResourceManager.GetString("Update Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available. Would you like to update?.
        /// </summary>
        public static string Update_Notify {
            get {
                return ResourceManager.GetString("Update Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the application is available. Would you like to update?.
        /// </summary>
        public static string UpdatePromptContent {
            get {
                return ResourceManager.GetString("UpdatePromptContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
